$JOB BUILD OMSI BASIC INTO BASIC.SV
.R PAL8
*DEBUG,EDIT/L$
.SA SYS BASEDT
.R PAL8
*DEBUG,COMPIL,ERROR/L$
.SA SYS COMPIL
.R PAL8
*DEBUG,RUN/L$
.SA SYS RUN
.R PIP
*BASIC.SV_BASEDT.SV,TM.TM,COMPIL.SV,RUN.SV/I
.DIR BASIC.SV
$END
